baseURL = "https://rodral.github.io/labveilletech"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Ma Veille Technologique"

paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addDot = true
  addFrame = true

  highlightColor = '#E63946'
  baseColor = "#F1FAEE"
  baseOffsetColor = "#1D3557"
  headingColor = "#457B9D"
  dotColor = "#A8DADC"
  textColor = "#1D3557"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      hardWraps = false
#      unsafe = true
#      xhtml = false

#[taxonomies]
#  category = 'categories'
#  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1

# [[menu.main]]
#    identifier = 'posts'
#   name = 'Posts'
#    url = '/posts/'
#    weight = 2
  
 # [[menu.main]]
 #   identifier = 'categories'
 #   name = 'Catégories'
 #   url = '/categories/'
 #   weight = 4

  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 5


  
